apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: swa10-homework
  labels:
    app: hello
    service: hello
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
      name: http
  selector:
    app: hello

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v1
  namespace: swa10-homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v1
  template:
    metadata:
      labels:
        app: hello
        version: v1
    spec:
      containers:
        - name: hello
          image: ditch0/swa10:v1
          ports:
            - containerPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-v2
  namespace: swa10-homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      version: v2
  template:
    metadata:
      labels:
        app: hello
        version: v2
    spec:
      containers:
        - name: hello
          image: ditch0/swa10:v2
          ports:
            - containerPort: 80
